name: Cleanup
on: push

jobs:
  clean:
    name: Cleanup
    runs-on: windows-latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      TZ: "Pacific/Auckland"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --use-feature=2020-resolver -r ./requirements.txt

      - name: Generate credentials
        run: |
          python aws_saml_login.py `
            --user ${{ secrets.AWS_USER }} `
            --password ${{ secrets.AWS_PASS}} `
            --token ${{ secrets.AWS_TOKEN }} `
            --idp iam.auckland.ac.nz

      - name: Pull windows downloads dir
        run: |
          aws --profile saml s3 sync `
            s3://r.docker.stat.auckland.ac.nz/downloads/Windows win

      - name: Upload installer
        run: |
          aws --profile saml s3 sync --dryrun `
            win s3://r.docker.stat.auckland.ac.nz/downloads/Windows

      - name: Generate index.html
        run: |
          aws --profile saml s3 ls s3://r.docker.stat.auckland.ac.nz/downloads/Windows/ > downloads_Windows.txt
          Rscript create_index.R downloads downloads/Windows

      - name: Push indices
        run: |
          aws --profile saml s3 sync `
            downloads s3://r.docker.stat.auckland.ac.nz/downloads

      - name: Clear cache
        run: |
          aws --profile 'saml' `
            cloudfront `
            create-invalidation `
            --distribution-id ${{ secrets.AWS_ID }} `
            --paths "/*"

  update-website:
    name: Update website
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send signal
        run: |
          curl -XPOST \
            -u "${{ secrets.PAT_USERNAME }}:${{ secrets.PAT_SECRET }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/iNZightVIT/inzight-www/actions/workflows/update-version.yaml/dispatches \
            --data '{"ref": "master"}'
