name: Nightly build
on: push
  # schedule:
  #   - cron: '0 0 * * *' # every night at 2am

jobs:
  build:
    name: Build nightly installer
    runs-on: windows-latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      TZ: "Pacific/Auckland"
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'

      - name: Install RGtk2
        run: library/iNZight/.github/install_gtk.cmd
        shell: bash

      - name: Add GTK to PATH
        run: echo "${{env.R_LIBS_USER}}\RGtk2\gtk\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Check RGtk2
        run: |
          library(RGtk2)
          gtkWindowNew()
        shell: Rscript {0}

      - name: Install packages
        run: Rscript install_nightly.R
