name: Release packages
on:
  push:
    branches:
      - master

jobs:
  sources:
    name: source
    runs-on: ubuntu-latest
    env:
      TZ: "Pacific/Auckland"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Cache python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --use-feature=2020-resolver -r ./requirements.txt

      - name: Generate credentials
        run: |
          python aws_saml_login.py \
            --user ${{ secrets.AWS_USER }} \
            --password ${{ secrets.AWS_PASS}} \
            --token ${{ secrets.AWS_TOKEN }} \
            --idp iam.auckland.ac.nz

      - name: Pull repository
        run: |
          mkdir -p src
          aws --profile saml s3 sync \
            s3://r.docker.stat.auckland.ac.nz/src \
            src

      - name: Build sources for updated packages
        env:
          OS_TYPE: ${{ runner.os }}
        run: Rscript build.R

      - name: Update HTML pages
        run: |
          python create_webpages.py --path src

      - name: Push repository
        run: |
          aws --profile saml s3 sync --dry --delete \
            src \
            s3://r.docker.stat.auckland.ac.nz/src

  binaries:
    name: windows binaries (${{ matrix.config.r }})
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: '3.6'}
          - {os: windows-latest, r: 'oldrel'}
          - {os: windows-latest, r: 'release'}
          - {os: windows-latest, r: 'devel'}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      TZ: "Pacific/Auckland"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-1-

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Cache python dependencies
        uses: actions/cache@v2
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install ./lxml-4.2.3-cp37-cp37m-win_amd64.whl
          pip install --use-feature=2020-resolver -r ./requirements.txt

      - name: Generate credentials
        run: |
          python aws_saml_login.py `
            --user ${{ secrets.AWS_USER }} `
            --password ${{ secrets.AWS_PASS}} `
            --token ${{ secrets.AWS_TOKEN }} `
            --idp iam.auckland.ac.nz

      - name: Pull repository
        run: |
          mkdir -p bin/windows
          aws --profile saml s3 sync `
            s3://r.docker.stat.auckland.ac.nz/bin/windows `
            bin/windows

      - name: Install RGtk2
        run: library/iNZight/.github/install_gtk.cmd
        shell: bash

      - name: Add GTK to PATH
        run: echo "::add-path::D:\a\_temp\Library\RGtk2\gtk\bin"

      - name: Install packages
        run: Rscript install.R

      - name: Build binaries for updated packages
        env:
          OS_TYPE: ${{ runner.os }}
        run: Rscript build.R

      - name: Update HTML pages
        run: |
          python create_webpages.py --path bin

      - name: Push repository
        run: |
          aws --profile saml s3 sync --dry --delete `
            bin/windows `
            s3://r.docker.stat.auckland.ac.nz/bin/windows
