name: Release packages
on:
  push:
    branches:
      - statsnz-datalab
    paths:
      - 'library/**'
      - 'installers/**'
      - '*.R'
      - '.github/**'

jobs:
  windows-installer:
    name: Deploy Windows installer
    if: "!contains(github.event.head_commit.message, 'skip installer')"
    runs-on: windows-latest
    continue-on-error: true
    needs: clearcache
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: '4.0'

      - name: Install iNZight
        working-directory: installers/win-installer
        run: Rscript install_inzight.R

      - name: Set iNZight version
        id: inzight
        run: echo "::set-output name=version::$(Rscript inzversion.R)"

      - name: Download GTK+
        run: |
          curl -L http://ftp.gnome.org/pub/gnome/binaries/win32/gtk+/2.22/gtk+-bundle_2.22.1-20101227_win32.zip -o gtk32.zip
          mkdir -p gtk/i386
          cd gtk/i386
          7z x ../../gtk32.zip

      - name: Add GTK+ to R library
        run: |
          mv gtk ${{ env.R_LIBS_USER }}/RGtk2

      - name: Move R and library to build location
        working-directory: installers/win-installer
        run: |
          mv C:/R R
          mv ${{ env.R_LIBS_USER }} library

      - name: Configure R GUI
        working-directory: installers/win-installer
        run: R\bin\Rscript.exe rgui_settings.R

      - name: Build installer
        working-directory: installers/win-installer
        run: makensis.exe inzight_installer.nsi
        env:
          INSTALLER_VERSION: ${{ steps.inzight.outputs.version }}

      - name: Upload artefact
        run: |
          mv installers/win-installer/iNZightVIT-installer.exe 
